"""The committed docs/agent/mcp-tools.md must match the generator's output.

The doc is generated from the live MCP registry and the kind/aspect dispatch
tables (`uv run python tools/gen_docs.py`). If a tool, parameter, or spec
field changes without regenerating, this test fails the gate.
"""

from __future__ import annotations

from tools import gen_docs


def test_committed_mcp_tools_doc_is_current() -> None:
    committed = gen_docs.OUTPUT_PATH.read_text(encoding="utf-8")
    assert committed == gen_docs.generate(), (
        "docs/agent/mcp-tools.md is stale; regenerate with "
        "`uv run python tools/gen_docs.py` (edit the generator or the "
        "dispatch tables, never the generated file)."
    )


def test_generated_doc_covers_every_registered_tool() -> None:
    text = gen_docs.OUTPUT_PATH.read_text(encoding="utf-8")
    assert text.startswith("# MCP Tools")
    assert "GENERATED by tools/gen_docs.py" in text
    # Kind-dispatched families carry per-kind spec subsections so empty-spec
    # probe calls stay optional.
    assert '### record_map_fact kind="relationship"' in text
    assert '### stage_revision kind="pattern_promotion"' in text
    assert '### record_observation kind="claim"' in text
    assert '- `kind="scan_only"`' in text
    assert '- `aspect="version_diff"` — requires `graph_role`' in text
    assert '- `aspect="profile_run"`' in text
