"""Regenerate docs/agent/mcp-tools.md from the live MCP registry.

The generated doc is the tool reference an agent reads instead of probing:
every registered tool's description and parameters (types, defaults, required
flags) from the FastMCP schemas, plus — for kind/aspect-dispatched tools —
one subsection per kind listing that kind's spec fields with a
required/optional split. Spec fields are introspected from the same dispatch
tables and handler signatures that ``mcp_tools._dispatch_kind`` validates
against, so the doc cannot drift from the targeted errors.

``tests/test_gen_docs.py`` regenerates the doc and compares it with the
committed file; edit this generator (or the dispatch tables), never the
generated markdown.

Usage:
    uv run python tools/gen_docs.py            # rewrite docs/agent/mcp-tools.md
    uv run python tools/gen_docs.py --check    # exit 1 if the committed file is stale
    uv run python tools/gen_docs.py --stdout   # print to stdout
"""

from __future__ import annotations

import argparse
import asyncio
import inspect
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OUTPUT_PATH = ROOT / "docs" / "agent" / "mcp-tools.md"

HEADER = """\
# MCP Tools

GENERATED by tools/gen_docs.py — edit the generator, not this file.

One section per registered tool, alphabetical. Parameters marked `required`
have no default; everything else shows its default. For kind/aspect-dispatched
tools, the per-kind subsections list exactly the fields that kind accepts —
a wrong or missing field fails with a targeted error naming the valid fields,
so probe calls are never necessary. Envelope rules (absent == null == empty,
truncation fields, suggestion shape) live in the `response_conventions` doc.
"""

# Flat-parameter kind/aspect tools enforce required fields inline rather than
# through handler signatures; mirror those checks here. Source of truth for
# each entry is named in the comment.
FLAT_REQUIRED: dict[str, dict[str, tuple[str, ...]]] = {
    # mcp_tools.export_preflight_tool: kind='context_slice' requires seed_iris.
    "doxabase.export_preflight": {"context_slice": ("seed_iris",)},
    # mcp_tools.list_revisions_tool: versions requires graph_role; resource
    # requires resource_iri.
    "doxabase.list_revisions": {
        "versions": ("graph_role",),
        "resource": ("resource_iri",),
    },
    # mcp_tools.describe_revision_tool: version_diff/graph_snapshot require
    # graph_role; resource_lineage requires resource_iri.
    "doxabase.describe_revision": {
        "version_diff": ("graph_role",),
        "resource_lineage": ("resource_iri",),
        "graph_snapshot": ("graph_role",),
    },
}


def _clean(text: str | None) -> str:
    """Collapse docstring indentation/newlines into one readable paragraph."""
    return re.sub(r"\s+", " ", text or "").strip()


def _schema_type(prop: dict[str, Any]) -> str:
    if "anyOf" in prop:
        return " | ".join(_schema_type(member) for member in prop["anyOf"])
    kind = prop.get("type")
    if kind == "array":
        items = prop.get("items")
        return f"array[{_schema_type(items)}]" if items else "array"
    return kind or "any"


def _param_lines(schema: dict[str, Any]) -> list[str]:
    """One line per parameter. Nullable-defaulting-to-null renders as just the
    value type: per response conventions, absent == null == empty."""
    required = set(schema.get("required", []))
    lines = []
    for name, prop in schema.get("properties", {}).items():
        rendered = _schema_type(prop)
        default = prop.get("default")
        if default is None:
            rendered = rendered.removesuffix(" | null")
        entry = f"- `{name}` ({rendered}"
        if name in required:
            entry += ", required)"
        elif default is not None:
            entry += f", default `{json.dumps(default)}`)"
        else:
            entry += ")"
        lines.append(entry)
    return lines


def _handler_spec_lines(handler: Any) -> list[str]:
    """Spec fields for one kind, split exactly as _dispatch_kind validates."""
    lines = []
    for name, parameter in inspect.signature(handler).parameters.items():
        if name == "db":
            continue
        annotation = parameter.annotation
        rendered = annotation if isinstance(annotation, str) else "any"
        if parameter.default is None:
            rendered = rendered.removesuffix(" | None")
        if parameter.default is inspect.Parameter.empty:
            lines.append(f"- `{name}` ({rendered}, required)")
        elif parameter.default is None:
            lines.append(f"- `{name}` ({rendered})")
        else:
            lines.append(f"- `{name}` ({rendered}, default `{parameter.default!r}`)")
    return lines


def _merged_spec_lines(core_method: Any, flat_names: set[str]) -> list[str]:
    """Spec fields for a flat+spec recorder: the core method's keyword surface
    minus the tool's flat parameters (mirrors _merge_spec_into_call)."""
    lines = []
    for name, parameter in inspect.signature(core_method).parameters.items():
        if name in {"self", "db"} or name in flat_names:
            continue
        annotation = parameter.annotation
        rendered = annotation if isinstance(annotation, str) else "any"
        if parameter.default is None:
            rendered = rendered.removesuffix(" | None")
        lines.append(f"- `{name}` ({rendered})")
    return lines


def _spec_kind_sections(tool_name: str, label: str, kinds: dict[str, Any]) -> list[str]:
    out = []
    for kind in sorted(kinds):
        out.append(f"### {tool_name.removeprefix('doxabase.')} {label}=\"{kind}\"")
        out.append("")
        out.extend(_handler_spec_lines(kinds[kind]))
        out.append("")
    return out


def _flat_kind_sections(
    tool_name: str,
    label: str,
    kind_params: dict[str, Any],
    shared: tuple[str, ...],
) -> list[str]:
    required_map = FLAT_REQUIRED.get(tool_name, {})
    out = [
        f"Shared parameters valid for every {label}: "
        + ", ".join(f"`{name}`" for name in shared)
        + ".",
        "",
    ]
    for kind in sorted(kind_params):
        required = required_map.get(kind, ())
        optional = sorted(set(kind_params[kind]) - set(required))
        parts = []
        if required:
            parts.append("requires " + ", ".join(f"`{name}`" for name in required))
        if optional:
            parts.append("accepts " + ", ".join(f"`{name}`" for name in optional))
        detail = "; ".join(parts) if parts else "no extra parameters"
        out.append(f"- `{label}=\"{kind}\"` — {detail}")
    out.append("")
    return out


def _describe_resource_sections(aspects: dict[str, dict[str, Any]]) -> list[str]:
    out = [
        "Aspects (`iri`, `graph`, and `aspect` always apply):",
        "",
    ]
    for aspect in sorted(aspects):
        info = aspects[aspect]
        parts = []
        if info["required"]:
            parts.append(
                "requires " + ", ".join(f"`{name}`" for name in info["required"])
            )
        if info["optional"]:
            parts.append(
                "accepts " + ", ".join(f"`{name}`" for name in info["optional"])
            )
        detail = "; ".join(parts)
        note = info["note"]
        suffix = f" — {detail}" if detail else ""
        out.append(f"- `aspect=\"{aspect}\"` ({note}){suffix}")
    out.append("")
    return out


def generate() -> str:
    from doxabase import mcp_tools as mt
    from doxabase.mcp_server import build_server

    with tempfile.TemporaryDirectory(prefix="doxabase-gen-docs-") as tmp:
        server = build_server(Path(tmp) / "unused.sqlite")
        tools = asyncio.run(server.list_tools())

    _OBS_FLATS = {
        "summary", "kind", "spec", "observed_asset", "observed_column",
        "observed_at", "observed_by", "evidence_summary", "evidence_sources",
    }
    _PATTERN_FLATS = {
        "summary", "pattern_text", "rationale", "pattern_targets",
        "supporting_observations", "supporting_claims", "evidence_summary",
        "evidence_sources", "source_path", "confidence", "map_implications",
        "spec",
    }
    _GREV_FLATS = {"summary", "rationale", "changed_graphs", "revision_type", "spec"}
    _RECON_FLATS = {
        "newer_claim", "older_claim", "relation", "rationale", "summary",
        "evidence_summary", "evidence_sources", "source_path", "spec",
    }
    import doxabase.core as _core

    extra_sections: dict[str, list[str]] = {
        "doxabase.record_pattern": [
            "Spec fields (long tail merged into the call; targeted errors "
            "name these):",
            "",
            *_merged_spec_lines(_core.DoxaBase.record_pattern, _PATTERN_FLATS),
        ],
        "doxabase.record_graph_revision": [
            "Spec fields:",
            "",
            *_merged_spec_lines(
                _core.DoxaBase.record_graph_revision, _GREV_FLATS
            ),
        ],
        "doxabase.record_claim_reconsideration": [
            "Spec fields:",
            "",
            *_merged_spec_lines(
                _core.DoxaBase.record_claim_reconsideration, _RECON_FLATS
            ),
        ],
        "doxabase.record_observation": [
            "Kinds `observation` (default) and `profile` use the flat "
            "parameters above plus these spec fields (merged into the call):",
            "",
            *_merged_spec_lines(_core.DoxaBase.record_observation, _OBS_FLATS),
            "",
            "Kinds `claim` and `query_result` take their "
            "fields in `spec` (top-level summary/observed/evidence flats "
            "are merged in):",
            "",
            *_spec_kind_sections(
                "doxabase.record_observation", "kind", mt._RECORD_OBSERVATION_SPEC_KINDS
            ),
        ],
        "doxabase.record_profile": _spec_kind_sections(
            "doxabase.record_profile", "kind", mt._RECORD_PROFILE_KINDS
        ),
        "doxabase.record_map_fact": _spec_kind_sections(
            "doxabase.record_map_fact", "kind", mt._RECORD_MAP_FACT_KINDS
        ),
        "doxabase.stage_revision": [
            *_spec_kind_sections(
                "doxabase.stage_revision", "kind", mt._STAGE_REVISION_KINDS
            ),
            "Dry-run planners (`dry_run=true`, nothing written; spec fields "
            "differ from the staging kind):",
            "",
            *_spec_kind_sections(
                "doxabase.stage_revision dry_run",
                "kind",
                mt._STAGE_REVISION_DRY_RUN_KINDS,
            ),
        ],
        "doxabase.export_bundle": _spec_kind_sections(
            "doxabase.export_bundle", "kind", mt._EXPORT_BUNDLE_KINDS
        ),
        "doxabase.import_bundle": _spec_kind_sections(
            "doxabase.import_bundle", "kind", mt._IMPORT_BUNDLE_KINDS
        ),
        "doxabase.export_preflight": _flat_kind_sections(
            "doxabase.export_preflight",
            "kind",
            mt._EXPORT_PREFLIGHT_KIND_PARAMS,
            mt._EXPORT_PREFLIGHT_SHARED_PARAMS,
        ),
        "doxabase.list_revisions": _flat_kind_sections(
            "doxabase.list_revisions",
            "kind",
            mt._LIST_REVISIONS_KIND_PARAMS,
            mt._LIST_REVISIONS_SHARED_PARAMS,
        ),
        "doxabase.describe_revision": _flat_kind_sections(
            "doxabase.describe_revision",
            "aspect",
            mt._DESCRIBE_REVISION_ASPECT_PARAMS,
            mt._DESCRIBE_REVISION_SHARED_PARAMS,
        ),
        "doxabase.describe_resource": _describe_resource_sections(
            mt._DESCRIBE_RESOURCE_ASPECTS
        ),
    }

    lines = [HEADER]
    for tool in sorted(tools, key=lambda item: item.name):
        lines.append(f"## {tool.name}")
        lines.append("")
        description = _clean(tool.description)
        if description:
            lines.append(description)
            lines.append("")
        lines.append("Parameters:")
        lines.append("")
        param_lines = _param_lines(tool.inputSchema)
        lines.extend(param_lines or ["- (none)"])
        lines.append("")
        lines.extend(extra_sections.get(tool.name, []))
    text = "\n".join(lines)
    return text.rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if stale")
    parser.add_argument("--stdout", action="store_true", help="print, do not write")
    args = parser.parse_args(argv)

    text = generate()
    if args.stdout:
        print(text, end="")
        return 0
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != text:
            print(f"{OUTPUT_PATH} is stale; run: uv run python tools/gen_docs.py")
            return 1
        print(f"{OUTPUT_PATH} is current")
        return 0
    OUTPUT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH} ({len(text):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
